name: CI integration test full

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'assert-equals/assert-equals'
      - 'assert-file-exists/assert-file-exists'
      - 'assert-file-not-exists/assert-file-not-exists'
      - 'assert-not-equals/assert-not-equals'

concurrency:
  group: integ-test
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  integ-tests:
    uses: ./.github/workflows/suite-integ-test.yml
    concurrency:
      group: CI-integ-test-full
      cancel-in-progress: false
    permissions:
      contents: read
      pull-requests: read
    with:
      runner-os: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      detect-changes: false
    secrets: inherit