name: CI integration test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: integ-test
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  integ-tests:
    name: Integration Tests
    uses: ./.github/workflows/suite-integ-test.yml
    permissions:
      contents: read
      pull-requests: read
    with:
      detect-changes: ${{ github.event_name == 'pull_request' }}
    secrets: inherit

  integ-tests-summary:
    name: Integration Tests Summary
    needs: integ-tests
    if: always()
    uses: ./.github/workflows/check-job-or-step-result.yml
    with:
      result: ${{ needs.integ-tests.result }}
