name: Test Assert Path Not Exists
on:
  workflow_call:
    inputs:
      runner-os:
        type: string
        default: '["ubuntu-latest"]'
      skip-dist:
        type: boolean
        default: false

env:
  SKIP_DIST: ${{ inputs.skip-dist }}

permissions:
  contents: read

jobs:
  before-all:
    name: Before All
    runs-on: ubuntu-latest
    outputs:
      existing-file-path: ${{ steps.create-temp-file.outputs.existing-file-path }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Initialize integration test
        uses: ./.github/actions/init-integ-test
      - name: Create Temp File
        id: create-temp-file
        run: |
          temp_file=$(mktemp test-file-XXXX.txt)
          echo "This is a test file." > "$temp_file"
          echo "existing-file-path=$temp_file" >> $GITHUB_OUTPUT
      - name: Create Artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          path: ${{ steps.create-temp-file.outputs.existing-file-path }}
          name: temp-file-path-not-exists
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  test-non-existent-path-with-message:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.runner-os) }}
    name: "GIVEN non-existent path, message='path should not exist' WHEN assert-path-not-exists THEN job is success"
    runs-on: ${{ matrix.os }}
    needs: before-all
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Initialize integration test
        uses: ./.github/actions/init-integ-test
      - name: Act
        id: act
        continue-on-error: true
        uses: ./assert-path-not-exists
        with:
          path: non-existent-path
          message: path should not exist
      - name: Assert step success
        uses: jaronline/action-assertions/assert-equals@2bbd7385b4aa7b2882f4b269addf795832e505fd # v1
        with:
          expected: success
          actual: ${{ steps.act.outcome }}

  test-non-existent-path-without-message:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.runner-os) }}
    name: "GIVEN non-existent path WHEN assert-path-not-exists THEN job is success"
    runs-on: ${{ matrix.os }}
    needs: before-all
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Initialize integration test
        uses: ./.github/actions/init-integ-test
      - name: Act
        id: act
        continue-on-error: true
        uses: ./assert-path-not-exists
        with:
          path: non-existent-path
      - name: Assert step success
        uses: jaronline/action-assertions/assert-equals@2bbd7385b4aa7b2882f4b269addf795832e505fd # v1
        with:
          expected: success
          actual: ${{ steps.act.outcome }}

  test-non-existent-glob-with-message:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.runner-os) }}
    name: "GIVEN non-existent glob, message='path should not exist' WHEN assert-path-not-exists THEN job is success"
    runs-on: ${{ matrix.os }}
    needs: before-all
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Initialize integration test
        uses: ./.github/actions/init-integ-test
      - name: Act
        id: act
        continue-on-error: true
        uses: ./assert-path-not-exists
        with:
          path: non/existent-*.txt
          match-method: glob
          message: path should not exist
      - name: Assert step success
        uses: jaronline/action-assertions/assert-equals@2bbd7385b4aa7b2882f4b269addf795832e505fd # v1
        with:
          expected: success
          actual: ${{ steps.act.outcome }}

  test-non-existent-glob-without-message:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.runner-os) }}
    name: "GIVEN non-existent glob WHEN assert-path-not-exists THEN job is success"
    runs-on: ${{ matrix.os }}
    needs: before-all
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Initialize integration test
        uses: ./.github/actions/init-integ-test
      - name: Act
        id: act
        continue-on-error: true
        uses: ./assert-path-not-exists
        with:
          path: non/existent-*.txt
          match-method: glob
      - name: Assert step success
        uses: jaronline/action-assertions/assert-equals@2bbd7385b4aa7b2882f4b269addf795832e505fd # v1
        with:
          expected: success
          actual: ${{ steps.act.outcome }}

  test-existing-path-with-message:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.runner-os) }}
    name: "GIVEN existing path, message='path should not exist' WHEN assert-path-not-exists THEN job is failure"
    runs-on: ${{ matrix.os }}
    needs: before-all
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Initialize integration test
        uses: ./.github/actions/init-integ-test
      - name: Download Temp File
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: temp-file-path-not-exists
      - name: Act
        id: act
        continue-on-error: true
        uses: ./assert-path-not-exists
        with:
          path: ${{ needs.before-all.outputs.existing-file-path }}
          message: path should not exist
      - name: Assert step failure
        uses: jaronline/action-assertions/assert-equals@2bbd7385b4aa7b2882f4b269addf795832e505fd # v1
        with:
          expected: failure
          actual: ${{ steps.act.outcome }}

  test-existing-path-without-message:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.runner-os) }}
    name: "GIVEN existing path WHEN assert-path-not-exists THEN job is failure"
    runs-on: ${{ matrix.os }}
    needs: before-all
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Initialize integration test
        uses: ./.github/actions/init-integ-test
      - name: Download Temp File
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: temp-file-path-not-exists
      - name: Act
        id: act
        continue-on-error: true
        uses: ./assert-path-not-exists
        with:
          path: ${{ needs.before-all.outputs.existing-file-path }}
      - name: Assert step failure
        uses: jaronline/action-assertions/assert-equals@2bbd7385b4aa7b2882f4b269addf795832e505fd # v1
        with:
          expected: failure
          actual: ${{ steps.act.outcome }}

  test-existing-glob-with-message:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.runner-os) }}
    name: "GIVEN existing glob, message='path should not exist' WHEN assert-path-not-exists THEN job is failure"
    runs-on: ${{ matrix.os }}
    needs: before-all
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Initialize integration test
        uses: ./.github/actions/init-integ-test
      - name: Act
        id: act
        continue-on-error: true
        uses: ./assert-path-not-exists
        with:
          path: .github/workflows/*.yml
          match-method: glob
          message: path should not exist
      - name: Assert step failure
        uses: jaronline/action-assertions/assert-equals@2bbd7385b4aa7b2882f4b269addf795832e505fd # v1
        with:
          expected: failure
          actual: ${{ steps.act.outcome }}

  test-existing-glob-without-message:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.runner-os) }}
    name: "GIVEN existing glob WHEN assert-path-not-exists THEN job is failure"
    runs-on: ${{ matrix.os }}
    needs: before-all
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Initialize integration test
        uses: ./.github/actions/init-integ-test
      - name: Act
        id: act
        continue-on-error: true
        uses: ./assert-path-not-exists
        with:
          path: .github/workflows/*.yml
          match-method: glob
      - name: Assert step failure
        uses: jaronline/action-assertions/assert-equals@2bbd7385b4aa7b2882f4b269addf795832e505fd # v1
        with:
          expected: failure
          actual: ${{ steps.act.outcome }}
